# Generated by Django 4.2.7 on 2025-12-31 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='official',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minute',
            name='agenda_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minute', to='meetings.agendaitem'),
        ),
        migrations.AddField(
            model_name='minute',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minute',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minute',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='meetings.minute'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendasection',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='meetings.agendasection'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('agenda_item', 'official')},
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['date', 'status'], name='meetings_date_fbb7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'published_at'], name='meetings_status_36024b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agendasection',
            unique_together={('meeting', 'order')},
        ),
        migrations.AddIndex(
            model_name='agendaitem',
            index=models.Index(fields=['meeting', 'order'], name='agenda_item_meeting_b62060_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaitem',
            index=models.Index(fields=['meeting', 'section'], name='agenda_item_meeting_72164d_idx'),
        ),
    ]
