# Generated by Django 4.2.7 on 2026-01-03 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_types', models.JSONField(default=list, help_text='List of subscription types: meeting_published, agenda_updated, minutes_approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unsubscribe_token', models.CharField(blank=True, max_length=64, unique=True)),
            ],
            options={
                'db_table': 'email_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='video_embed_code',
            field=models.TextField(blank=True, help_text='Raw embed code if needed', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='video_type',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('direct', 'Direct URL'), ('embed', 'Embed Code')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, or direct video URL', null=True),
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(blank=True, help_text='For public attendees without accounts', max_length=200)),
                ('attendee_email', models.EmailField(blank=True, max_length=254)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('attendance_type', models.CharField(choices=[('official', 'Elected Official'), ('staff', 'Staff'), ('public', 'Public Attendee'), ('virtual', 'Virtual Attendee')], default='public', max_length=20)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='meetings.meeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_attendances',
                'ordering': ['-check_in_time'],
                'indexes': [models.Index(fields=['meeting', 'check_in_time'], name='meeting_att_meeting_e4ae98_idx')],
            },
        ),
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_id', models.IntegerField()),
                ('signature_type', models.CharField(choices=[('approval', 'Approval'), ('acknowledgment', 'Acknowledgment'), ('consent', 'Consent')], default='approval', max_length=20)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signature_data', models.TextField(blank=True, help_text='Base64 encoded signature or digital signature', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'electronic_signatures',
                'ordering': ['-signed_at'],
                'unique_together': {('document_type', 'document_id', 'signed_by')},
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_id', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('access_type', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('print', 'Print')], default='view', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_access_logs',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['document_type', 'document_id'], name='document_ac_documen_d4f543_idx'), models.Index(fields=['accessed_at'], name='document_ac_accesse_3cc6e4_idx')],
            },
        ),
    ]
