# Generated by Django 4.2.7 on 2025-12-31 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['agenda_item', 'is_current'], name='attachments_agenda__f3c8b1_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['file_type', 'is_public'], name='attachments_file_ty_242b07_idx'),
        ),
    ]
